### ISSUE TITLE
Issues loosely/temporally related to Penn team Griduniverse sprint

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Dallinger#1400]
A to-be-ordered list of issues pulled from various sources.

- [ ] Fix Griduniverse tests. Theres a Dallinger merge that breaks Griduniverse (We think its regarding locking and unlocking the database ?)
- [ ] Strategy for merging https://github.com/Dallinger/Griduniverse/tree/reliability-and-stats (split off ghosting work from stats work, FoodSeekingBot, and other reliability work?)
- [ ] https://github.com/Dallinger/Griduniverse/issues/201, fixed in `reliability-and-stats` branch
- [ ] https://github.com/Dallinger/Griduniverse/issues/204 Error adding non-working participant to grid/game
- [ ] https://github.com/Dallinger/Griduniverse/issues/203 Implementation of is_complete() needs improvement
- [ ] Dallinger #1399 No Infos in DB bug
- [ ] Dallinger  #1398 MTurk's ApproveAssignment called on assignment not yet submitted
- [ ] https://github.com/Dallinger/Griduniverse/issues/202 Qualification does not exist error
- [ ] https://github.com/Dallinger/Griduniverse/issues/196 Hang at waiting room with mix of humans and bots (may be fixed in https://github.com/Dallinger/Dallinger/pull/1385)
- [ ] https://github.com/Dallinger/Griduniverse/issues/205 Error on `move` event
- [ ] https://github.com/Dallinger/Griduniverse/issues/206 Slow player spawning on Grid
- [ ] Document basic explanation of the role of web vs. worker dynos, and provide some general guidelines on how to choose numbers for the related config values
- [ ] Investigate low yield for Penn MTurk recruitments, and presence of `spectator` participants
- [ ] https://github.com/Dallinger/Dallinger/issues/1402 Heruko files (clock.py, launch.py, and worker.py) should be copied from dallinger git remote, rather than local installation used to deploy
- [ ] https://github.com/Dallinger/Dallinger/issues/1403 It's painful to debug errors returned from `git` calls (via `subprocess.check_call()` in `dallinger.utils.GitClient`)

**Comment by vlall** [comment]
I'm gathering that "Dallinger/Griduniverse#203 Implementation of is_complete() needs improvement"
might be complete now according to @alecpm's statement here: https://github.com/Dallinger/Griduniverse/issues/203

**Comment by alecpm** [comment]
Unfortunately not, we’ve fixed some issues related to logs posted on that ticket, but the fundamental issues with the GU `is_complete` remain.

**Comment by vlall** [comment]
I believe these all have been addressed.
